"""Initial migration. Backend fully setup and database also setup

Revision ID: 84d1dd9b6471
Revises: 
Create Date: 2024-11-06 15:01:19.432482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d1dd9b6471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_passengers', 'passengers', ['passenger_id'], ['passenger_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_passengert', type_='foreignkey')
        batch_op.drop_column('passenger_id')

    # ### end Alembic commands ###
