"""empty message

Revision ID: 9c57c4f80889
Revises: 075a1037861b
Create Date: 2024-11-07 00:36:14.880322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c57c4f80889'
down_revision = '075a1037861b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('flight_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('origin',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('flight_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('departure_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('arrival_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('available_seats',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('available_seats',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('arrival_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('departure_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('flight_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('origin',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('flight_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
